name: gdp
channels:
  - conda-forge
  - danielfrg
dependencies:
  - danielfrg::apache-livy
  - beakerx
  - bqplot
  - conda>=4.7.11
  - geojson
  - geopy
  - ipyleaflet>=0.11.1
  - ipympl
  - ipyvolume
  - ipywidgets
  - jupyterlab
  - pip
  - pip:
    - "-r requirements.txt"
  - python=3.7
  - pyspark
  - qgrid
  - requests
  - scipy
  - sparkmagic
  - tqdm
  - voila 
