name: gdp
channels:
  - conda-forge
  - danielfrg
dependencies:
  - aiohttp
  - anaconda-client
  - danielfrg::apache-livy
  - asciinema
  - awscli
  - beakerx
  - black
  - bqplot
  - bokeh
  - boto3
  - botocore
  - conda>=4.7.11
  - contextily
  - deprecated
  - fastparquet
  - ffmpeg
  - flask
  - fiona>=1.8
  - geojson
  - geopy
  - geoviews
  - gdal
  - holoviews
  - imagemagick
  - ipyleaflet>=0.11.1
  - ipympl
  - ipytree
  - ipyvolume
  - ipywidgets
  - jupyterlab
  - lua
  - luarocks
  - luigi
  - matplotlib>=3.1.1
  - nbdime
  - nltk>=3.4.4
  - numpy>=1.17
  - opencv
  - overpy
  - papermill
  - pip
  - pip:
    - "-r requirements.txt"
  - protobuf
  - pyarrow
  - python=3.7
  - pypy3.5
  - pyspark>=2.4
  - pytest>=5
  - qgrid
  - requests
  - requests-oauthlib
  - reportlab
  - rust
  - seaborn
  - selenium
  - scikit-image
  - scikit-learn
  - scipy
  - shapely>=1.6
  - snappy
  - spacy>=2.1.8
  - sparkmagic
  - sphinx>=2.1.2
  - svglib
  - timeout-decorator
  - tqdm
  - voila
  - watermark
  - xarray  
