name: gdp
channels:
  - conda-forge
  - danielfrg
dependencies:
  - danielfrg::apache-livy
  - beakerx
  - bqplot
  - bokeh
  - conda>=4.7.11
  - contextily
  - deprecated
  - geojson
  - geopy
  - gdal
  - ipyleaflet>=0.11.1
  - ipympl
  - ipyvolume
  - ipywidgets
  - jupyterlab
  - pip
  - pip:
    - "-r requirements.txt"
  - protobuf
  - python=3.7
  - pyspark
  - qgrid
  - requests
  - requests-oauthlib
  - reportlab
  - selenium
  - scipy
  - sparkmagic
  - svglib
  - timeout-decorator
  - tqdm
  - voila 
