name: gdp
channels:
  - conda-forge
  - danielfrg
dependencies:
  - danielfrg::apache-livy
  - asciinema
  - beakerx
  - black
  - bqplot
  - bokeh
  - boto3
  - botocore
  - conda>=4.7.11
  - contextily
  - deprecated
  - ffmpeg
  - geojson
  - geopy
  - geoviews
  - gdal
  - holoviews
  - imagemagick
  - ipyleaflet>=0.11.1
  - ipympl
  - ipyrest
  - ipytree
  - ipyvolume
  - ipywidgets
  - jupyterlab
  - matplotlib
  - nbdime
  - nltk
  - numpy
  - opencv
  - papermill
  - pip
  - pip:
    - "-r requirements.txt"
  - protobuf
  - pyarrow
  - python=3.7
  - pypy3.5
  - pyspark
  - qgrid
  - requests
  - requests-oauthlib
  - reportlab
  - rust
  - seaborn
  - selenium
  - scikit-image
  - scikit-learn
  - scipy
  - spacy
  - sparkmagic
  - svglib
  - timeout-decorator
  - tqdm
  - voila
  - xarray
