name: gdp
channels:
  - conda-forge
dependencies:
  - beakerx
  - conda>=4.7.11
  - julia
  - jupyterlab>=1.0.5
  - lua
  - luarocks
  - octave_kernel
  - pip
  - pip:
    - "-r requirements.txt"
  - python=3.7
  - xeus-cling
