name: gdp
channels:
  - conda-forge
dependencies:
  - conda>=4.7.11
  - jupyterlab>=1.0.5
  - libspatialite>=4.3.0a
  - libspatialindex>=1.9.0
  - pip
  - pip:
    - "-r requirements.txt"
  - python=3.7
  - rust
  - voila>=0.1.9
