name: gdp
channels:
  - conda-forge
  - danielfrg
dependencies:
  - aiohttp
  - anaconda-client
  - danielfrg::apache-livy
  - asciinema
  - awscli
  - beakerx
  - black
  - bqplot
  - bokeh
  - boto3
  - botocore
  - conda>=4.7.11
  - contextily
  - deprecated
  - fastparquet
  - ffmpeg
  - flask
  - geojson
  - geopy
  - geoviews
  - gdal
  - ghostscript>=9.22
  - gnuplot>=5.2.7
  - holoviews
  - imagemagick
  - ipyleaflet>=0.11.1
  - ipympl
  - ipytree
  - ipyvolume
  - ipywidgets
  - jupyterlab>=1.0.5
  - libspatialite>=4.3.0a
  - libspatialindex>=1.9.0
  - lua
  - luarocks
  - luigi
  - matplotlib
  - nbdime
  - nltk
  - numpy>=1.17.0
  - octave
  - octave_kernel>=0.31.0
  - opencv
  - overpy
  - papermill
  - pip
  - pip:
    - "-r requirements.txt"
  - protobuf
  - pyarrow
  - python=3.7
  - pypy3.5
  - pyspark
  - pytest>=5
  - qgrid
  - requests
  - requests-oauthlib
  - reportlab
  - seaborn
  - selenium
  - scikit-image
  - scikit-learn
  - scipy
  - shapely
  - snappy
  - spacy
  - sparkmagic
  - sphinx
  - svglib
  - timeout-decorator
  - tqdm
  - voila
  - watermark
  - xarray  
